### ISSUE TITLE
get this error!

### ISSUE THREAD

**Issue by lordmen99** [palavatv/palava-web#55]
i have setup palava-web and get this error when access mydomain:8080

` Sorry, but we could not detect the required WebRTC technology in your web browser.

In order to be able to use palava.tv, you will need install a web browser which supports WebRTC, such as Firefox. If you are in luck, you just need to update your current browser to the latest version.

`

**Comment by farao** [comment]
Which browser (type and version number) are you using?

**Comment by paulgoetze** [comment]
Closing this issue due to missing information.
