### ISSUE TITLE
FireFox 95 can't detect media streams

### ISSUE THREAD

**Issue by pascalwengerter** [palavatv/palava-web#87]
Currently, Palava.tv is not usable for me with FireFox since it can't detect media streams. No error logs in the console or other issues, just nothing happening where a prompt for camera/microphone would be expected

**Comment by paulgoetze** [comment]
@pascalwengerter I just checked for 
* Firefox 95.0 on desktop (Kubuntu 21.10) 
* Firefox 95.1.0 on mobile (Android 9)

Both seem to work fine for me when being connected over WiFi.

Could you share more information about your operating system and whether you were on WiFi or mobile connection when you saw the media stream issues?

**Comment by pascalwengerter** [comment]
Interesting...was connected to WiFi on my Ubuntu 21.XX (or sth, quite recent definitely) and have come across it some weeks ago already

**Comment by pascalwengerter** [comment]
Can confirm it works fine on Android ;)

**Comment by pascalwengerter** [comment]
Weirdly enough a system restart fixed this. 
From my experience with other videocall tools, I also suspected other consumers of media streams (e.g. Zoom) not correctly terminating, but entered and left a Zoom call and could still successfully use Palava.tv afterwards (also after the restart, that is)

Sorry for the noise 🤗
